#!/bin/bash
# =============================================================================
# setup_coredns.sh
# =============================================================================
# Reads spoofing.conf and generates CoreDNS zone files for every spoofed
# domain. Then updates the Corefile to include all spoofed domains and
# restarts CoreDNS.
#
# Usage (on Azure VM as root):
#   chmod +x /etc/coredns/setup_coredns.sh
#   sudo bash /etc/coredns/setup_coredns.sh
# =============================================================================

set -euo pipefail

CONF="/etc/coredns/spoofing.conf"
ZONES="/etc/coredns/zones"
COREFILE="/etc/coredns/Corefile"
COREFILE_TEMPLATE="/etc/coredns/Corefile.tpl"

mkdir -p "$ZONES"

# ── Step 1: Generate zone files from spoofing.conf ───────────────────────────
echo "[*] Generating zone files..."
SPOOFED_DOMAINS=""

while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip comments and blank lines
    [[ "$line" =~ ^#.*$ || -z "${line// }" ]] && continue

    domain=$(echo "$line" | awk '{print $1}')
    ip=$(echo "$line" | awk '{print $2}')

    [[ -z "$domain" || -z "$ip" ]] && continue

    SERIAL=$(date +%Y%m%d%H)
    cat > "$ZONES/$domain.zone" <<ZONE
\$ORIGIN $domain.
@   3600 IN SOA ns1.$domain. admin.$domain. $SERIAL 3600 900 604800 300
@   3600 IN NS  ns1.$domain.
*      0 IN A   $ip
@      0 IN A   $ip
ZONE

    echo "    [+] $domain → $ip"
    SPOOFED_DOMAINS="$SPOOFED_DOMAINS $domain"
done < "$CONF"

# ── Step 2: Rebuild Corefile from template ────────────────────────────────────
echo "[*] Rebuilding Corefile..."

# Write header
cat > "$COREFILE" <<'EOF'
# Auto-generated by setup_coredns.sh – DO NOT EDIT MANUALLY
# Edit spoofing.conf and re-run setup_coredns.sh instead.

EOF

# Add a block per spoofed domain
while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^#.*$ || -z "${line// }" ]] && continue
    domain=$(echo "$line" | awk '{print $1}')
    [[ -z "$domain" ]] && continue

    cat >> "$COREFILE" <<BLOCK
$domain {
    file /etc/coredns/zones/$domain.zone
    log
    errors
}

BLOCK
done < "$CONF"

# Add fixed blocks for exfil, c2, and default forwarder
# NOTE: randInt is NOT available in the standard CoreDNS template plugin.
#       We use static IPs instead. The wildcard match (any subdomain) still works.
cat >> "$COREFILE" <<'EOF'
exfil.lab {
    template IN A {
        answer "{{ .Name }} 0 IN A 203.0.113.100"
    }
    log
    errors
}

c2.lab {
    template IN A {
        answer "{{ .Name }} 0 IN A 198.51.100.100"
    }
    template IN TXT {
        answer "{{ .Name }} 0 IN TXT \"beacon_ack_1234\""
    }
    template IN CNAME {
        answer "{{ .Name }} 0 IN CNAME relay.c2.lab."
    }
    log
    errors
}

. {
    forward . 8.8.8.8 8.8.4.4
    cache 30
    log
    errors
    health :8080
}
EOF

echo "[*] Corefile written to $COREFILE"

# ── Step 3: Restart CoreDNS ───────────────────────────────────────────────────
if systemctl list-units --all coredns.service | grep -q coredns; then
    echo "[*] Restarting CoreDNS..."
    systemctl restart coredns
    sleep 2
    systemctl status coredns --no-pager -l
else
    echo "[!] CoreDNS service unit not found – copy coredns.service to /etc/systemd/system/ first"
fi

echo ""
echo "[OK] Setup complete. Test with:"
echo "     dig @$(hostname -I | awk '{print $1}') google.com"
echo "     dig @$(hostname -I | awk '{print $1}') chunk1.exfil.lab"
echo "     dig @$(hostname -I | awk '{print $1}') beacon1.c2.lab"
